services:
  message_scheduler:
    image: ghcr.io/rubenbejanyan/message-scheduler:latest
    container_name: message_scheduler
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - infra_net
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 256m

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.41
    command: --interval 60 message_scheduler
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

networks:
  infra_net:
    external: true
    name: infra_net
